spring:
  datasource:
    url: jdbc:mysql://192.168.154.219:3306/ying_note?characterEncoding=UTF-8&useSSL=false
    username: testnote
    password: Testnote@2018
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    cn.sunguolei.note: debug