server:
  port: 8080
spring:
  application:
    name: front

  profiles:
#    active: prod
    active: dev

  mvc:
    favicon:
      enabled: false

  datasource:
    url: jdbc:mysql://192.168.154.219:3306/ying_note?characterEncoding=UTF-8&useSSL=false
    username: testnote
    password: Testnote@2018
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.sunguolei.note.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.sunguolei.note: debug