spring:
  datasource:
    url: jdbc:mysql://192.168.154.219:3306/ying_note?characterEncoding=UTF-8&useSSL=false
    username: testnote
    password: Testnote@2018
    driver-class-name: com.mysql.jdbc.Driver

  mail:
    host: smtp.163.com
    username: yingnote_dev@163.com
    password: dSjal1985ganeL28
    properties:
        mail:
            smtp:
                auth: true
                timeout: 25000
logging:
  level:
    cn.sunguolei.note: debug